### ISSUE TITLE
Does the library have a mobile preview ? 

### ISSUE THREAD

**Issue by constantin-pwrr-expert** [Mesoptier/react-serp-preview#12]

**Comment by Mesoptier** [comment]
No, it does not have a specific mobile preview. Though, by setting the `width` parameter to a small value you can get something that at least fits on mobile devices: 
![image](https://user-images.githubusercontent.com/322632/111145816-fb1d9b00-8588-11eb-8459-3fd2d53b2566.png)

For more specific mobile preview behaviour, you could open a PR. What did you have in mind?

**Comment by constantin-pwrr-expert** [comment]
I can't open a PR, there is no development done from my side. Today I was just browsing around to see what solutions are there for a react project and came across this library. 
As a mobile view suggestion or what we are going to go for is something like the design from here -> https://technicalseo.com/tools/google-serp-simulator/

![image](https://user-images.githubusercontent.com/56354870/111146424-14771500-8592-11eb-92e9-f33e6c9fb1d5.png)
